export const apiMainRoutes = {
  getHome: '/home',
  getTranslates: '/translations',
  getTeams: '/teams',
  getVolunteers: '/volunteers',
  getPartners: '/partners',
  getCompetitions: '/competitions',
  getLogos: '/logos',
  getAboutHeroes: '/about-heroes',
  getContacts:'/contacts',
  getHomeFormHeroes: '/home-form-heroes',
  getHomeGalleries: '/home-galleries',
  getQuestions: '/home-questions',
  getSocials: '/social-footer',
  getProducts: '/products',
  getProductById: '/products/:id',
  getCategories: '/products/by-types',
  getCompetitionDetail: '/competitions/slug/:slug',
  getCompetitionTerms: '/competitions/:slug/consent-text',
  getCompetitionRules: '/competitions/:slug/rules',
  getParticipants: '/competitions/:slug/participants',
  getQualities: '/keyfiyets',
  getCompetitionBanner: '/competition-banners',
  getResults: '/competitions/results',
  getResult: '/competitions/:slug/results',
  getCompetitionGallery: 'competitions/slug/:slug/gallery-years',
  getPartnerCompetitions: '/partners/competitions',
  getSeoPage: '/seo',
  getCalendarEvents: '/calendar-events',
  getCalendarEventsUpcoming: '/calendar-events/upcoming'
};
